---
apiVersion: v1
kind: Pod
metadata:
  name: media
spec:
  containers:
    - name: jellyfin
      image: ghcr.io/jellyfin/jellyfin:10
      env:
        - name: JELLYFIN_PublishedServerUrl
          value: http://192.168.1.100
      ports:
        # http webui
        - containerPort: 8096
          hostPort: 8096
          protocol: TCP
        # https webui
        - containerPort: 8920
          hostPort: 8920
          protocol: TCP
        # service discovery
        - containerPort: 7359
          hostPort: 7359
          protocol: UDP
        # DLNA service discovery
        - containerPort: 1900
          hostPort: 1900
          protocol: UDP
      volumeMounts:
        - mountPath: /config
          name: jellyfin-config-pvc
        - mountPath: /media
          name: shared-data-pvc

    - name: filebrowser
      image: docker.io/filebrowser/filebrowser:v2
      env:
        - name: FB_PORT
          value: 8080
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - mountPath: /srv
          name: shared-data-pvc
        - mountPath: /database
          name: filebrowser-database-pvc

  volumes:
    - name: shared-data-pvc
      PersistentVolumeClaim:
        claimName: media-shared-data

    - name: jellyfin-config-pvc
      PersistentVolumeClaim:
        claimName: media-jellyfin-config

    - name: filebrowser-database-pvc
      PersistentVolumeClaim:
        claimName: media-filebrowser-database
