---
apiVersion: v1
kind: ConfigMap
metadata:
  name: media-filebrowser-config
data:
  config.yaml: |
    server:
      database: /data/filebrowser.db
      sources:
        - name: media
          path: /srv
          config:
            defaultEnabled: true
---
apiVersion: v1
kind: Pod
metadata:
  name: media
spec:
  containers:
    - name: jellyfin
      image: ghcr.io/jellyfin/jellyfin:10
      env:
        - name: JELLYFIN_PublishedServerUrl
          value: http://192.168.1.100
      ports:
        # http webui
        - containerPort: 8096
          hostPort: 8096
          protocol: TCP
        # https webui
        - containerPort: 8920
          hostPort: 8920
          protocol: TCP
        # service discovery
        - containerPort: 7359
          hostPort: 7359
          protocol: UDP
        # DLNA service discovery
        - containerPort: 1900
          hostPort: 1900
          protocol: UDP
      volumeMounts:
        - mountPath: /config
          name: jellyfin-config-pvc
        - mountPath: /media
          name: shared-data-pvc

    - name: filebrowser
      image: ghcr.io/gtsteffaniak/filebrowser:stable-slim
      env:
        - name: FILEBROWSER_CONFIG
          value: /config/config.yaml
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - mountPath: /srv
          name: shared-data-pvc
        - mountPath: /data
          name: filebrowser-data-pvc
        - mountPath: /config
          name: filebrowser-config

  volumes:
    - name: shared-data-pvc
      persistentVolumeClaim:
        claimName: media-shared-data

    - name: jellyfin-config-pvc
      persistentVolumeClaim:
        claimName: media-jellyfin-config

    - name: filebrowser-data-pvc
      persistentVolumeClaim:
        claimName: media-filebrowser-data

    - name: filebrowser-config
      configMap:
        name: media-filebrowser-config
